Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).

You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
October 22, 2023 - 16:21:56
Django version 4.2.4, using settings 'kbo_demo.settings'
Starting development server at http://127.0.0.1:10000/
Quit the server with CONTROL-C.

2019 SV R
[22/Oct/2023 16:24:24] "POST /status/statistics/ HTTP/1.1" 200 9849
[9.34227183]
[3.6818251]
[22/Oct/2023 16:24:34] "GET /status/ml/ HTTP/1.1" 200 606
[4.33752315]
[1.38242052]
[22/Oct/2023 16:24:37] "POST /status/ml/ HTTP/1.1" 200 608
[22/Oct/2023 23:21:00] "GET /status/statistics HTTP/1.1" 301 0
2023 ERA IP
[22/Oct/2023 23:21:00] "GET /status/statistics/ HTTP/1.1" 200 10063
Not Found: /favicon.ico
[22/Oct/2023 23:21:00] "GET /favicon.ico HTTP/1.1" 404 2224
2020 HLD HBP
[22/Oct/2023 23:21:07] "POST /status/statistics/ HTTP/1.1" 200 9943
2023 ERA IP
[22/Oct/2023 23:21:12] "GET /status/statistics/ HTTP/1.1" 200 10063
Not Found: /apple-touch-icon-152x152-precomposed.png
[22/Oct/2023 23:21:13] "GET /apple-touch-icon-152x152-precomposed.png HTTP/1.1" 404 2311
Not Found: /apple-touch-icon-152x152.png
[22/Oct/2023 23:21:13] "GET /apple-touch-icon-152x152.png HTTP/1.1" 404 2275
Not Found: /apple-touch-icon-precomposed.png
[22/Oct/2023 23:21:13] "GET /apple-touch-icon-precomposed.png HTTP/1.1" 404 2287
Not Found: /apple-touch-icon.png
[22/Oct/2023 23:21:13] "GET /apple-touch-icon.png HTTP/1.1" 404 2251
Not Found: /favicon.ico
[22/Oct/2023 23:21:13] "GET /favicon.ico HTTP/1.1" 404 2224
Not Found: /apple-touch-icon-152x152-precomposed.png
[22/Oct/2023 23:21:13] "GET /apple-touch-icon-152x152-precomposed.png HTTP/1.1" 404 2311
Not Found: /apple-touch-icon-152x152.png
[22/Oct/2023 23:21:14] "GET /apple-touch-icon-152x152.png HTTP/1.1" 404 2275
Not Found: /apple-touch-icon-precomposed.png
[22/Oct/2023 23:21:14] "GET /apple-touch-icon-precomposed.png HTTP/1.1" 404 2287
Not Found: /apple-touch-icon.png
[22/Oct/2023 23:21:14] "GET /apple-touch-icon.png HTTP/1.1" 404 2251
Not Found: /favicon.ico
[22/Oct/2023 23:21:14] "GET /favicon.ico HTTP/1.1" 404 2224
[9.34227183]
[3.6818251]
[23/Oct/2023 04:47:43] "GET /status/ml/ HTTP/1.1" 200 606
2023 ERA IP
[23/Oct/2023 04:47:51] "GET /status/statistics/ HTTP/1.1" 200 10063
2021 ERA IP
[23/Oct/2023 04:47:58] "POST /status/statistics/ HTTP/1.1" 200 10859
2021 HLD IP
[23/Oct/2023 04:48:04] "POST /status/statistics/ HTTP/1.1" 200 10634
2009 W IP
[23/Oct/2023 04:48:24] "POST /status/statistics/ HTTP/1.1" 200 9279
2009 WHIP IP
[23/Oct/2023 04:49:13] "POST /status/statistics/ HTTP/1.1" 200 9443
2009 W IP
[23/Oct/2023 04:49:27] "POST /status/statistics/ HTTP/1.1" 200 9279
2004 HLD IP
[23/Oct/2023 04:49:53] "POST /status/statistics/ HTTP/1.1" 200 9103
[9.34227183]
[3.6818251]
[23/Oct/2023 04:59:27] "GET /status/ml/ HTTP/1.1" 200 606
2023 ERA IP
[23/Oct/2023 05:13:40] "GET /status/statistics/ HTTP/1.1" 200 10063
[9.34227183]
[3.6818251]
[23/Oct/2023 05:19:38] "GET /status/ml/ HTTP/1.1" 200 606
2023 ERA IP
[23/Oct/2023 16:21:24] "GET /status/statistics/ HTTP/1.1" 200 10063
2023 ERA IP
[23/Oct/2023 16:21:53] "GET /status/statistics/ HTTP/1.1" 200 10063
Not Found: /favicon.ico
[23/Oct/2023 16:21:54] "GET /favicon.ico HTTP/1.1" 404 2224
[9.34227183]
[3.6818251]
[23/Oct/2023 16:21:56] "GET /status/ml/ HTTP/1.1" 200 606
2018 W IP
[23/Oct/2023 16:22:16] "POST /status/statistics/ HTTP/1.1" 200 10204
[9.34227183]
[3.6818251]
[23/Oct/2023 16:22:17] "GET /status/ml/ HTTP/1.1" 200 606
2009 SV BB
[23/Oct/2023 16:22:24] "POST /status/statistics/ HTTP/1.1" 200 9060
[4.33752315]
[1.38242052]
[23/Oct/2023 16:22:30] "POST /status/ml/ HTTP/1.1" 200 608
[4.33752315]
[1.38242052]
[23/Oct/2023 16:22:32] "POST /status/ml/ HTTP/1.1" 200 608
[4.33752315]
[1.38242052]
[23/Oct/2023 16:22:33] "POST /status/ml/ HTTP/1.1" 200 608
[9.34227183]
[3.6818251]
[23/Oct/2023 16:22:41] "GET /status/ml/ HTTP/1.1" 200 606
2023 ERA IP
[23/Oct/2023 16:22:57] "GET /status/statistics/ HTTP/1.1" 200 10063
2023 ERA IP
[27/Oct/2023 01:50:16] "GET /status/statistics/ HTTP/1.1" 200 10063
[9.34227183]
[3.6818251]
[27/Oct/2023 07:50:09] "GET /status/ml/ HTTP/1.1" 200 606
2023 ERA IP
[27/Oct/2023 08:23:34] "GET /status/statistics/ HTTP/1.1" 200 10063
[9.34227183]
[3.6818251]
[27/Oct/2023 08:23:36] "GET /status/ml/ HTTP/1.1" 200 606
[29/Oct/2023 02:00:56] "GET /status/ml HTTP/1.1" 301 0
[9.34227183]
[3.6818251]
[29/Oct/2023 02:00:56] "GET /status/ml/ HTTP/1.1" 200 606
Not Found: /favicon.ico
[29/Oct/2023 02:00:57] "GET /favicon.ico HTTP/1.1" 404 2224
2023 ERA IP
[29/Oct/2023 02:01:14] "GET /status/statistics/ HTTP/1.1" 200 10063
2023 ERA IP
[29/Oct/2023 02:03:55] "GET /status/statistics/ HTTP/1.1" 200 10063
[9.34227183]
[3.6818251]
[29/Oct/2023 02:04:03] "GET /status/ml/ HTTP/1.1" 200 606
[9.34227183]
[3.6818251]
[29/Oct/2023 02:04:04] "GET /status/ml/ HTTP/1.1" 200 606
[9.34227183]
[3.6818251]
[29/Oct/2023 02:04:05] "GET /status/ml/ HTTP/1.1" 200 606
[9.34227183]
[3.6818251]
[29/Oct/2023 02:04:05] "GET /status/ml/ HTTP/1.1" 200 606
2023 ERA IP
[29/Oct/2023 02:04:12] "GET /status/statistics/ HTTP/1.1" 200 10063
2023 ERA IP
[29/Oct/2023 02:05:09] "GET /status/statistics/ HTTP/1.1" 200 10063
2023 ERA IP
[29/Oct/2023 02:05:10] "GET /status/statistics/ HTTP/1.1" 200 10063
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).

You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
November 06, 2023 - 06:37:02
Django version 4.2.4, using settings 'kbo_demo.settings'
Starting development server at http://127.0.0.1:10000/
Quit the server with CONTROL-C.

2023 ERA IP
[06/Nov/2023 06:37:38] "GET /status/statistics/ HTTP/1.1" 200 10063
Not Found: /status/ã…¢/
[06/Nov/2023 06:37:54] "GET /status/%E3%85%A2/ HTTP/1.1" 404 2642
[9.34227183]
[3.6818251]
[06/Nov/2023 06:38:03] "GET /status/ml/ HTTP/1.1" 200 606
[9.34227183]
[3.6818251]
[06/Nov/2023 06:39:30] "GET /status/ml/ HTTP/1.1" 200 606
[9.34227183]
[3.6818251]
[06/Nov/2023 06:39:34] "GET /status/ml/ HTTP/1.1" 200 606
[4.33752315]
[1.38242052]
[06/Nov/2023 06:39:37] "POST /status/ml/ HTTP/1.1" 200 608
2023 ERA IP
[06/Nov/2023 06:39:44] "GET /status/statistics/ HTTP/1.1" 200 10063
2023 L IP
[06/Nov/2023 06:39:47] "POST /status/statistics/ HTTP/1.1" 200 9844
[06/Nov/2023 06:41:06] "GET /status/statistics HTTP/1.1" 301 0
2023 ERA IP
[06/Nov/2023 06:41:06] "GET /status/statistics/ HTTP/1.1" 200 10063
2023 ERA IP
[06/Nov/2023 06:41:10] "GET /status/statistics/ HTTP/1.1" 200 10063
Not Found: /favicon.ico
[06/Nov/2023 06:41:12] "GET /favicon.ico HTTP/1.1" 404 2224
Not Found: /images/branding/googlelogo/2x/googlelogo_light_color_92x30dp.png
[06/Nov/2023 06:41:14] "GET /images/branding/googlelogo/2x/googlelogo_light_color_92x30dp.png HTTP/1.1" 404 2383
2023 WPCT IP
[07/Nov/2023 01:57:34] "POST /status/statistics/ HTTP/1.1" 200 8981
[9.34227183]
[3.6818251]
[07/Nov/2023 01:57:39] "GET /status/ml/ HTTP/1.1" 200 606
[1.85992479]
[0.24410143]
[07/Nov/2023 01:57:43] "POST /status/ml/ HTTP/1.1" 200 608
[-0.61767357]
[-0.89421767]
[07/Nov/2023 01:57:45] "POST /status/ml/ HTTP/1.1" 200 610
[3.3464838]
[0.92709288]
[07/Nov/2023 01:57:49] "POST /status/ml/ HTTP/1.1" 200 607
[6.8151215]
[2.52073962]
[07/Nov/2023 01:57:57] "POST /status/ml/ HTTP/1.1" 200 606
[5.57632232]
[1.95158007]
[07/Nov/2023 01:58:00] "POST /status/ml/ HTTP/1.1" 200 607
Not Found: /status/status/
[07/Nov/2023 01:58:06] "GET /status/status/ HTTP/1.1" 404 2645
[07/Nov/2023 01:58:10] "GET /status/ HTTP/1.1" 200 435262
Not Found: /status/statistica
[07/Nov/2023 01:58:43] "GET /status/statistica HTTP/1.1" 404 2654
[07/Nov/2023 01:58:45] "GET /status/statistics HTTP/1.1" 301 0
2023 ERA IP
[07/Nov/2023 01:58:45] "GET /status/statistics/ HTTP/1.1" 200 10063
2023 ERA WHIP
[07/Nov/2023 01:58:51] "POST /status/statistics/ HTTP/1.1" 200 9927
2010 ERA WHIP
[07/Nov/2023 01:59:08] "POST /status/statistics/ HTTP/1.1" 200 9226
2010 SO WHIP
[07/Nov/2023 01:59:13] "POST /status/statistics/ HTTP/1.1" 200 9205
2009 SO WHIP
[07/Nov/2023 01:59:20] "POST /status/statistics/ HTTP/1.1" 200 9232
2021 SO WHIP
[07/Nov/2023 01:59:25] "POST /status/statistics/ HTTP/1.1" 200 10568
2022 SO WHIP
[07/Nov/2023 01:59:29] "POST /status/statistics/ HTTP/1.1" 200 10402
2021 SO WHIP
[07/Nov/2023 01:59:33] "POST /status/statistics/ HTTP/1.1" 200 10568
2023 SO WHIP
[07/Nov/2023 01:59:36] "POST /status/statistics/ HTTP/1.1" 200 9860
2020 SO WHIP
[07/Nov/2023 01:59:41] "POST /status/statistics/ HTTP/1.1" 200 10354
2019 SO WHIP
[07/Nov/2023 01:59:44] "POST /status/statistics/ HTTP/1.1" 200 10084
2018 SO WHIP
[07/Nov/2023 01:59:47] "POST /status/statistics/ HTTP/1.1" 200 10142
2016 SO WHIP
Internal Server Error: /status/statistics/
Traceback (most recent call last):
  File "/Users/michaelkim/anaconda3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelkim/anaconda3/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelkim/Documents/KBO/demo/kbo_demo/status/views.py", line 77, in result
    plotData, fullData = makeData(current_year, current_x, current_y)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelkim/Documents/KBO/demo/kbo_demo/status/views.py", line 113, in makeData
    y_val = words[STATS_INDEX[y]]
            ~~~~~^^^^^^^^^^^^^^^^
IndexError: list index out of range
[07/Nov/2023 01:59:51] "POST /status/statistics/ HTTP/1.1" 500 81003
2016 SO WHIP
Internal Server Error: /status/statistics/
Traceback (most recent call last):
  File "/Users/michaelkim/anaconda3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelkim/anaconda3/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelkim/Documents/KBO/demo/kbo_demo/status/views.py", line 77, in result
    plotData, fullData = makeData(current_year, current_x, current_y)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelkim/Documents/KBO/demo/kbo_demo/status/views.py", line 113, in makeData
    y_val = words[STATS_INDEX[y]]
            ~~~~~^^^^^^^^^^^^^^^^
IndexError: list index out of range
[07/Nov/2023 01:59:57] "POST /status/statistics/ HTTP/1.1" 500 81003
2023 ERA IP
[07/Nov/2023 02:00:02] "GET /status/statistics/ HTTP/1.1" 200 10063
2015 ERA IP
[07/Nov/2023 02:00:06] "POST /status/statistics/ HTTP/1.1" 200 10159
2015 SO WHIP
Internal Server Error: /status/statistics/
Traceback (most recent call last):
  File "/Users/michaelkim/anaconda3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelkim/anaconda3/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelkim/Documents/KBO/demo/kbo_demo/status/views.py", line 77, in result
    plotData, fullData = makeData(current_year, current_x, current_y)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelkim/Documents/KBO/demo/kbo_demo/status/views.py", line 113, in makeData
    y_val = words[STATS_INDEX[y]]
            ~~~~~^^^^^^^^^^^^^^^^
IndexError: list index out of range
[07/Nov/2023 02:00:16] "POST /status/statistics/ HTTP/1.1" 500 79820
2021 SO WHIP
[07/Nov/2023 02:00:30] "POST /status/statistics/ HTTP/1.1" 200 10568
2014 SO WHIP
Internal Server Error: /status/statistics/
Traceback (most recent call last):
  File "/Users/michaelkim/anaconda3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelkim/anaconda3/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelkim/Documents/KBO/demo/kbo_demo/status/views.py", line 77, in result
    plotData, fullData = makeData(current_year, current_x, current_y)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelkim/Documents/KBO/demo/kbo_demo/status/views.py", line 113, in makeData
    y_val = words[STATS_INDEX[y]]
            ~~~~~^^^^^^^^^^^^^^^^
IndexError: list index out of range
[07/Nov/2023 02:00:33] "POST /status/statistics/ HTTP/1.1" 500 80326
2014 R WHIP
Internal Server Error: /status/statistics/
Traceback (most recent call last):
  File "/Users/michaelkim/anaconda3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelkim/anaconda3/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelkim/Documents/KBO/demo/kbo_demo/status/views.py", line 77, in result
    plotData, fullData = makeData(current_year, current_x, current_y)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelkim/Documents/KBO/demo/kbo_demo/status/views.py", line 113, in makeData
    y_val = words[STATS_INDEX[y]]
            ~~~~~^^^^^^^^^^^^^^^^
IndexError: list index out of range
[07/Nov/2023 02:00:41] "POST /status/statistics/ HTTP/1.1" 500 80327
2004 R WHIP
Internal Server Error: /status/statistics/
Traceback (most recent call last):
  File "/Users/michaelkim/anaconda3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelkim/anaconda3/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelkim/Documents/KBO/demo/kbo_demo/status/views.py", line 77, in result
    plotData, fullData = makeData(current_year, current_x, current_y)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelkim/Documents/KBO/demo/kbo_demo/status/views.py", line 113, in makeData
    y_val = words[STATS_INDEX[y]]
            ~~~~~^^^^^^^^^^^^^^^^
IndexError: list index out of range
[07/Nov/2023 02:00:45] "POST /status/statistics/ HTTP/1.1" 500 75261
2004 R ER
[07/Nov/2023 02:00:49] "POST /status/statistics/ HTTP/1.1" 200 9038
2004 R SO
[07/Nov/2023 02:00:51] "POST /status/statistics/ HTTP/1.1" 200 9051
2004 R WPCT
[07/Nov/2023 02:00:55] "POST /status/statistics/ HTTP/1.1" 200 8508
2004 R WHIP
Internal Server Error: /status/statistics/
Traceback (most recent call last):
  File "/Users/michaelkim/anaconda3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelkim/anaconda3/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelkim/Documents/KBO/demo/kbo_demo/status/views.py", line 77, in result
    plotData, fullData = makeData(current_year, current_x, current_y)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelkim/Documents/KBO/demo/kbo_demo/status/views.py", line 113, in makeData
    y_val = words[STATS_INDEX[y]]
            ~~~~~^^^^^^^^^^^^^^^^
IndexError: list index out of range
[07/Nov/2023 02:00:59] "POST /status/statistics/ HTTP/1.1" 500 75261
2009 R WHIP
[07/Nov/2023 02:01:09] "POST /status/statistics/ HTTP/1.1" 200 9224
2004 WHIP SO
Internal Server Error: /status/statistics/
Traceback (most recent call last):
  File "/Users/michaelkim/anaconda3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelkim/anaconda3/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelkim/Documents/KBO/demo/kbo_demo/status/views.py", line 77, in result
    plotData, fullData = makeData(current_year, current_x, current_y)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelkim/Documents/KBO/demo/kbo_demo/status/views.py", line 112, in makeData
    x_val = words[STATS_INDEX[x]]
            ~~~~~^^^^^^^^^^^^^^^^
IndexError: list index out of range
[07/Nov/2023 02:01:18] "POST /status/statistics/ HTTP/1.1" 500 75300
2004 WHIP R
Internal Server Error: /status/statistics/
Traceback (most recent call last):
  File "/Users/michaelkim/anaconda3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelkim/anaconda3/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelkim/Documents/KBO/demo/kbo_demo/status/views.py", line 77, in result
    plotData, fullData = makeData(current_year, current_x, current_y)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelkim/Documents/KBO/demo/kbo_demo/status/views.py", line 112, in makeData
    x_val = words[STATS_INDEX[x]]
            ~~~~~^^^^^^^^^^^^^^^^
IndexError: list index out of range
[07/Nov/2023 02:01:24] "POST /status/statistics/ HTTP/1.1" 500 75297
2004 ER R
[07/Nov/2023 02:01:27] "POST /status/statistics/ HTTP/1.1" 200 9040
2021 WHIP R
[07/Nov/2023 02:01:32] "POST /status/statistics/ HTTP/1.1" 200 10545
2022 WHIP R
[07/Nov/2023 02:01:36] "POST /status/statistics/ HTTP/1.1" 200 10369
2019 WHIP R
[07/Nov/2023 02:01:39] "POST /status/statistics/ HTTP/1.1" 200 10053
2015 WHIP R
Internal Server Error: /status/statistics/
Traceback (most recent call last):
  File "/Users/michaelkim/anaconda3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelkim/anaconda3/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelkim/Documents/KBO/demo/kbo_demo/status/views.py", line 77, in result
    plotData, fullData = makeData(current_year, current_x, current_y)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelkim/Documents/KBO/demo/kbo_demo/status/views.py", line 112, in makeData
    x_val = words[STATS_INDEX[x]]
            ~~~~~^^^^^^^^^^^^^^^^
IndexError: list index out of range
[07/Nov/2023 02:01:42] "POST /status/statistics/ HTTP/1.1" 500 79844
2016 WHIP R
Internal Server Error: /status/statistics/
Traceback (most recent call last):
  File "/Users/michaelkim/anaconda3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelkim/anaconda3/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelkim/Documents/KBO/demo/kbo_demo/status/views.py", line 77, in result
    plotData, fullData = makeData(current_year, current_x, current_y)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelkim/Documents/KBO/demo/kbo_demo/status/views.py", line 112, in makeData
    x_val = words[STATS_INDEX[x]]
            ~~~~~^^^^^^^^^^^^^^^^
IndexError: list index out of range
[07/Nov/2023 02:01:45] "POST /status/statistics/ HTTP/1.1" 500 81029
2017 WHIP R
[07/Nov/2023 02:01:49] "POST /status/statistics/ HTTP/1.1" 200 9875
2014 WHIP R
Internal Server Error: /status/statistics/
Traceback (most recent call last):
  File "/Users/michaelkim/anaconda3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelkim/anaconda3/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelkim/Documents/KBO/demo/kbo_demo/status/views.py", line 77, in result
    plotData, fullData = makeData(current_year, current_x, current_y)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelkim/Documents/KBO/demo/kbo_demo/status/views.py", line 112, in makeData
    x_val = words[STATS_INDEX[x]]
            ~~~~~^^^^^^^^^^^^^^^^
IndexError: list index out of range
[07/Nov/2023 02:01:52] "POST /status/statistics/ HTTP/1.1" 500 80362
2013 WHIP R
[07/Nov/2023 02:01:54] "POST /status/statistics/ HTTP/1.1" 200 9263
2012 WHIP R
[07/Nov/2023 02:01:57] "POST /status/statistics/ HTTP/1.1" 200 9181
2006 WHIP R
[07/Nov/2023 02:02:00] "POST /status/statistics/ HTTP/1.1" 200 8969
2008 WHIP R
[07/Nov/2023 02:02:02] "POST /status/statistics/ HTTP/1.1" 200 9138
2004 WHIP R
Internal Server Error: /status/statistics/
Traceback (most recent call last):
  File "/Users/michaelkim/anaconda3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelkim/anaconda3/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelkim/Documents/KBO/demo/kbo_demo/status/views.py", line 77, in result
    plotData, fullData = makeData(current_year, current_x, current_y)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelkim/Documents/KBO/demo/kbo_demo/status/views.py", line 112, in makeData
    x_val = words[STATS_INDEX[x]]
            ~~~~~^^^^^^^^^^^^^^^^
IndexError: list index out of range
[07/Nov/2023 02:02:05] "POST /status/statistics/ HTTP/1.1" 500 75297
2003 WHIP R
Internal Server Error: /status/statistics/
Traceback (most recent call last):
  File "/Users/michaelkim/anaconda3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelkim/anaconda3/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelkim/Documents/KBO/demo/kbo_demo/status/views.py", line 77, in result
    plotData, fullData = makeData(current_year, current_x, current_y)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelkim/Documents/KBO/demo/kbo_demo/status/views.py", line 112, in makeData
    x_val = words[STATS_INDEX[x]]
            ~~~~~^^^^^^^^^^^^^^^^
IndexError: list index out of range
[07/Nov/2023 02:02:08] "POST /status/statistics/ HTTP/1.1" 500 79045
2003 WHIP R
Internal Server Error: /status/statistics/
Traceback (most recent call last):
  File "/Users/michaelkim/anaconda3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelkim/anaconda3/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelkim/Documents/KBO/demo/kbo_demo/status/views.py", line 77, in result
    plotData, fullData = makeData(current_year, current_x, current_y)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelkim/Documents/KBO/demo/kbo_demo/status/views.py", line 112, in makeData
    x_val = words[STATS_INDEX[x]]
            ~~~~~^^^^^^^^^^^^^^^^
IndexError: list index out of range
[07/Nov/2023 02:02:14] "POST /status/statistics/ HTTP/1.1" 500 79045
2012 WHIP R
[07/Nov/2023 02:02:22] "POST /status/statistics/ HTTP/1.1" 200 9181
2012 HLD R
[07/Nov/2023 02:02:28] "POST /status/statistics/ HTTP/1.1" 200 9042
2003 HLD R
[07/Nov/2023 02:02:32] "POST /status/statistics/ HTTP/1.1" 200 8827
2003 HLD R
[07/Nov/2023 02:02:54] "POST /status/statistics/ HTTP/1.1" 200 8827
2023 ERA IP
[07/Nov/2023 02:03:21] "POST /status/statistics/ HTTP/1.1" 200 10063
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).

You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
November 10, 2023 - 01:16:45
Django version 4.2.4, using settings 'kbo_demo.settings'
Starting development server at http://127.0.0.1:10000/
Quit the server with CONTROL-C.

2023 ERA IP
[10/Nov/2023 01:17:02] "POST /status/statistics/ HTTP/1.1" 200 10063
[9.34227183]
[3.6818251]
[10/Nov/2023 01:17:15] "GET /status/ml/ HTTP/1.1" 200 606
[4.33752315]
[1.38242052]
[10/Nov/2023 01:17:34] "POST /status/ml/ HTTP/1.1" 200 608
[6.8151215]
[2.52073962]
[10/Nov/2023 01:17:38] "POST /status/ml/ HTTP/1.1" 200 606
2023 ERA IP
[10/Nov/2023 01:17:43] "GET /status/statistics/ HTTP/1.1" 200 10063
2014 WHIP IP
Internal Server Error: /status/statistics/
Traceback (most recent call last):
  File "/Users/michaelkim/anaconda3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelkim/anaconda3/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelkim/Documents/KBO/demo/kbo_demo/status/views.py", line 77, in result
    plotData, fullData = makeData(current_year, current_x, current_y)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelkim/Documents/KBO/demo/kbo_demo/status/views.py", line 112, in makeData
    x_val = words[STATS_INDEX[x]]
            ~~~~~^^^^^^^^^^^^^^^^
IndexError: list index out of range
[10/Nov/2023 01:17:49] "POST /status/statistics/ HTTP/1.1" 500 80488
2014 R IP
[10/Nov/2023 01:17:53] "POST /status/statistics/ HTTP/1.1" 200 9601
2009 R IP
[10/Nov/2023 01:55:48] "POST /status/statistics/ HTTP/1.1" 200 9405
2009 R IP
[10/Nov/2023 01:55:51] "POST /status/statistics/ HTTP/1.1" 200 9405
2009 WPCT IP
[10/Nov/2023 01:55:57] "POST /status/statistics/ HTTP/1.1" 200 8776
2020 WPCT IP
[10/Nov/2023 01:56:02] "POST /status/statistics/ HTTP/1.1" 200 9685
2020 HR IP
[10/Nov/2023 01:56:05] "POST /status/statistics/ HTTP/1.1" 200 10405
2012 HR IP
[10/Nov/2023 01:56:09] "POST /status/statistics/ HTTP/1.1" 200 9267
2012 ER IP
[10/Nov/2023 01:56:12] "POST /status/statistics/ HTTP/1.1" 200 9372
2021 ER IP
[10/Nov/2023 01:56:46] "POST /status/statistics/ HTTP/1.1" 200 10796
2021 WPCT IP
[10/Nov/2023 01:56:50] "POST /status/statistics/ HTTP/1.1" 200 9698
[9.34227183]
[3.6818251]
[10/Nov/2023 01:56:54] "GET /status/ml/ HTTP/1.1" 200 606
[4.33752315]
[1.38242052]
[10/Nov/2023 01:56:58] "POST /status/ml/ HTTP/1.1" 200 608
2023 ERA IP
[10/Nov/2023 01:57:03] "GET /status/statistics/ HTTP/1.1" 200 10063
2023 ERA IP
[10/Nov/2023 01:57:12] "GET /status/statistics/ HTTP/1.1" 200 10063
Not Found: /favicon.ico
[10/Nov/2023 01:57:13] "GET /favicon.ico HTTP/1.1" 404 2220
2023 ERA IP
[10/Nov/2023 05:11:55] "GET /status/statistics/ HTTP/1.1" 200 10063
Not Found: /
[10/Nov/2023 05:12:52] "GET / HTTP/1.1" 404 2169
2023 ERA IP
[10/Nov/2023 05:44:50] "GET /status/statistics/ HTTP/1.1" 200 10063
2023 SV IP
[10/Nov/2023 05:44:56] "POST /status/statistics/ HTTP/1.1" 200 9854
2023 BB IP
[10/Nov/2023 05:45:06] "POST /status/statistics/ HTTP/1.1" 200 9955
[9.34227183]
[3.6818251]
[10/Nov/2023 05:45:09] "GET /status/ml/ HTTP/1.1" 200 606
[4.33752315]
[1.38242052]
[10/Nov/2023 05:45:13] "POST /status/ml/ HTTP/1.1" 200 608
[4.33752315]
[1.38242052]
[10/Nov/2023 05:45:22] "POST /status/ml/ HTTP/1.1" 200 608
2023 ERA IP
[10/Nov/2023 05:45:29] "GET /status/statistics/ HTTP/1.1" 200 10063
2023 ERA IP
[10/Nov/2023 05:46:05] "GET /status/statistics/ HTTP/1.1" 200 10063
2023 ERA IP
[10/Nov/2023 05:46:05] "GET /status/statistics/ HTTP/1.1" 200 10063
Not Found: /apple-touch-icon-precomposed.png
[10/Nov/2023 05:46:06] "GET /apple-touch-icon-precomposed.png HTTP/1.1" 404 2287
Not Found: /apple-touch-icon.png
[10/Nov/2023 05:46:06] "GET /apple-touch-icon.png HTTP/1.1" 404 2251
Not Found: /favicon.ico
[10/Nov/2023 05:46:06] "GET /favicon.ico HTTP/1.1" 404 2224
Not Found: /apple-touch-icon-precomposed.png
[10/Nov/2023 05:46:06] "GET /apple-touch-icon-precomposed.png HTTP/1.1" 404 2287
Not Found: /favicon.ico
[10/Nov/2023 05:46:06] "GET /favicon.ico HTTP/1.1" 404 2224
Not Found: /apple-touch-icon-precomposed.png
[10/Nov/2023 05:46:06] "GET /apple-touch-icon-precomposed.png HTTP/1.1" 404 2287
Not Found: /apple-touch-icon.png
Not Found: /apple-touch-icon.png
[10/Nov/2023 05:46:06] "GET /apple-touch-icon.png HTTP/1.1" 404 2251
[10/Nov/2023 05:46:06] "GET /apple-touch-icon.png HTTP/1.1" 404 2251
Not Found: /favicon.ico
[10/Nov/2023 05:46:07] "GET /favicon.ico HTTP/1.1" 404 2224
2023 ERA IP
[10/Nov/2023 05:46:07] "GET /status/statistics/ HTTP/1.1" 200 10063
Not Found: /apple-touch-icon-precomposed.png
[10/Nov/2023 05:46:07] "GET /apple-touch-icon-precomposed.png HTTP/1.1" 404 2287
Not Found: /apple-touch-icon.png
[10/Nov/2023 05:46:07] "GET /apple-touch-icon.png HTTP/1.1" 404 2251
Not Found: /favicon.ico
[10/Nov/2023 05:46:07] "GET /favicon.ico HTTP/1.1" 404 2224
Not Found: /apple-touch-icon-precomposed.png
[10/Nov/2023 05:46:07] "GET /apple-touch-icon-precomposed.png HTTP/1.1" 404 2287
Not Found: /apple-touch-icon.png
[10/Nov/2023 05:46:07] "GET /apple-touch-icon.png HTTP/1.1" 404 2251
Not Found: /favicon.ico
[10/Nov/2023 05:46:07] "GET /favicon.ico HTTP/1.1" 404 2224
2023 ERA BB
[10/Nov/2023 05:46:15] "POST /status/statistics/ HTTP/1.1" 200 9846
2017 WHIP BB
[10/Nov/2023 05:46:21] "POST /status/statistics/ HTTP/1.1" 200 9850
2017 WHIP BB
[10/Nov/2023 05:46:22] "POST /status/statistics/ HTTP/1.1" 200 9850
2015 WHIP BB
Internal Server Error: /status/statistics/
Traceback (most recent call last):
  File "/Users/michaelkim/anaconda3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelkim/anaconda3/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelkim/Documents/KBO/demo/kbo_demo/status/views.py", line 77, in result
    plotData, fullData = makeData(current_year, current_x, current_y)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelkim/Documents/KBO/demo/kbo_demo/status/views.py", line 112, in makeData
    x_val = words[STATS_INDEX[x]]
            ~~~~~^^^^^^^^^^^^^^^^
IndexError: list index out of range
[10/Nov/2023 05:46:26] "POST /status/statistics/ HTTP/1.1" 500 78821
[9.34227183]
[3.6818251]
[10/Nov/2023 05:46:32] "GET /status/ml/ HTTP/1.1" 200 606
[4.33752315]
[1.38242052]
[10/Nov/2023 05:46:36] "POST /status/ml/ HTTP/1.1" 200 608
2023 ERA IP
[10/Nov/2023 11:23:13] "GET /status/statistics/ HTTP/1.1" 200 10063
2023 ERA HBP
[10/Nov/2023 11:39:43] "POST /status/statistics/ HTTP/1.1" 200 9744
2023 ERA HBP
[11/Nov/2023 02:19:37] "POST /status/statistics/ HTTP/1.1" 200 9744
2023 ERA HBP
[12/Nov/2023 06:42:29] "POST /status/statistics/ HTTP/1.1" 200 9744
2023 ERA HBP
[12/Nov/2023 23:09:12] "POST /status/statistics/ HTTP/1.1" 200 9744
2023 ERA IP
[12/Nov/2023 23:13:40] "POST /status/statistics/ HTTP/1.1" 200 10063
[9.34227183]
[3.6818251]
[12/Nov/2023 23:13:46] "GET /status/ml/ HTTP/1.1" 200 606
[4.33752315]
[1.38242052]
[12/Nov/2023 23:13:50] "POST /status/ml/ HTTP/1.1" 200 608
2023 ERA IP
[12/Nov/2023 23:13:53] "GET /status/statistics/ HTTP/1.1" 200 10063
2023 ERA IP
[13/Nov/2023 14:29:49] "GET /status/statistics/ HTTP/1.1" 200 10063
Not Found: /robots.txt
[14/Nov/2023 00:11:20] "GET /robots.txt HTTP/1.1" 404 2221
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).

You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
November 14, 2023 - 00:51:58
Django version 4.2.4, using settings 'kbo_demo.settings'
Starting development server at http://127.0.0.1:10000/
Quit the server with CONTROL-C.

2023 ERA IP
[14/Nov/2023 00:52:11] "POST /status/statistics/ HTTP/1.1" 200 10063
Not Found: /favicon.ico
[14/Nov/2023 00:52:11] "GET /favicon.ico HTTP/1.1" 404 2224
2023 SV IP
[14/Nov/2023 00:52:14] "POST /status/statistics/ HTTP/1.1" 200 9854
[9.34227183]
[3.6818251]
[14/Nov/2023 00:52:28] "GET /status/ml/ HTTP/1.1" 200 606
[4.33752315]
[1.38242052]
[14/Nov/2023 00:52:32] "POST /status/ml/ HTTP/1.1" 200 608
2023 ERA IP
[14/Nov/2023 00:52:36] "GET /status/statistics/ HTTP/1.1" 200 10063
Not Found: /robots.txt
[14/Nov/2023 09:52:49] "GET /robots.txt HTTP/1.1" 404 2221
2023 ERA IP
[14/Nov/2023 09:52:50] "GET /status/statistics/ HTTP/1.1" 200 10063
Not Found: /sitemap.xml
[14/Nov/2023 09:53:03] "GET /sitemap.xml HTTP/1.1" 404 2224
Not Found: /robots.txt
[14/Nov/2023 20:19:06] "GET /robots.txt HTTP/1.1" 404 2221
[9.34227183]
[3.6818251]
[14/Nov/2023 20:19:07] "GET /status/ml/ HTTP/1.1" 200 606
2023 ERA IP
[15/Nov/2023 07:41:05] "GET /status/statistics/ HTTP/1.1" 200 10063
2023 ERA IP
[15/Nov/2023 14:40:43] "GET /status/statistics/ HTTP/1.1" 200 10063
Not Found: /robots.txt
[16/Nov/2023 09:24:07] "GET /robots.txt HTTP/1.1" 404 2221
2023 ERA IP
[16/Nov/2023 09:24:11] "GET /status/statistics/ HTTP/1.1" 200 10063
[9.34227183]
[3.6818251]
[16/Nov/2023 09:24:17] "GET /status/ml/ HTTP/1.1" 200 606
Not Found: /robots.txt
[16/Nov/2023 13:55:20] "GET /robots.txt HTTP/1.1" 404 2221
2023 ERA IP
[16/Nov/2023 13:55:21] "GET /status/statistics/ HTTP/1.1" 200 10063
2023 ERA IP
[17/Nov/2023 01:43:07] "GET /status/statistics/ HTTP/1.1" 200 10063
2023 W IP
[18/Nov/2023 01:24:27] "POST /status/statistics/ HTTP/1.1" 200 9843
2023 W IP
[18/Nov/2023 01:24:34] "POST /status/statistics/ HTTP/1.1" 200 9843
2023 W BB
[18/Nov/2023 01:24:38] "POST /status/statistics/ HTTP/1.1" 200 9631
[9.34227183]
[3.6818251]
[18/Nov/2023 01:24:43] "GET /status/ml/ HTTP/1.1" 200 606
[4.33752315]
[1.38242052]
[18/Nov/2023 01:24:48] "POST /status/ml/ HTTP/1.1" 200 608
2023 ERA IP
[18/Nov/2023 01:24:53] "GET /status/statistics/ HTTP/1.1" 200 10063
Not Found: /robots.txt
[18/Nov/2023 01:28:27] "GET /robots.txt HTTP/1.1" 404 2221
2023 ERA IP
[18/Nov/2023 01:28:58] "GET /status/statistics/ HTTP/1.1" 200 10063
2023 ERA BB
[18/Nov/2023 11:09:37] "POST /status/statistics/ HTTP/1.1" 200 9846
2023 WPCT BB
[18/Nov/2023 11:09:53] "POST /status/statistics/ HTTP/1.1" 200 8815
2023 ERA IP
[19/Nov/2023 09:23:08] "GET /status/statistics/ HTTP/1.1" 200 10063
2023 BB BB
[20/Nov/2023 03:01:01] "POST /status/statistics/ HTTP/1.1" 200 9742
2023 BB R
[20/Nov/2023 08:02:18] "POST /status/statistics/ HTTP/1.1" 200 9754
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).

You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
November 20, 2023 - 11:18:29
Django version 4.2.4, using settings 'kbo_demo.settings'
Starting development server at http://127.0.0.1:10000/
Quit the server with CONTROL-C.

2023 BB R
[20/Nov/2023 11:18:38] "POST /status/statistics/ HTTP/1.1" 200 9754
2023 R ER
[20/Nov/2023 11:18:44] "POST /status/statistics/ HTTP/1.1" 200 9758
[9.34227183]
[3.6818251]
[20/Nov/2023 11:19:05] "GET /status/ml/ HTTP/1.1" 200 606
[4.33752315]
[1.38242052]
[20/Nov/2023 11:19:09] "POST /status/ml/ HTTP/1.1" 200 608
2023 ERA IP
[20/Nov/2023 11:19:15] "GET /status/statistics/ HTTP/1.1" 200 10063
Not Found: /robots.txt
[20/Nov/2023 23:00:31] "GET /robots.txt HTTP/1.1" 404 2221
Not Found: /robots.txt
[20/Nov/2023 23:00:31] "GET /robots.txt HTTP/1.1" 404 2221
Not Found: /sitemap.xml
[20/Nov/2023 23:00:32] "GET /sitemap.xml HTTP/1.1" 404 2224
2023 W IP
[23/Nov/2023 11:39:57] "POST /status/statistics/ HTTP/1.1" 200 9843
2023 ERA IP
[24/Nov/2023 15:05:11] "POST /status/statistics/ HTTP/1.1" 200 10063
[9.34227183]
[3.6818251]
[24/Nov/2023 15:05:17] "GET /status/ml/ HTTP/1.1" 200 606
[4.33752315]
[1.38242052]
[24/Nov/2023 15:05:21] "POST /status/ml/ HTTP/1.1" 200 608
Internal Server Error: /status/ml/
Traceback (most recent call last):
  File "/Users/michaelkim/anaconda3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelkim/anaconda3/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelkim/Documents/KBO/demo/kbo_demo/status/views.py", line 145, in ml
    era, whip = predict(float(current_ip))
                        ^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'd'
[24/Nov/2023 15:05:24] "POST /status/ml/ HTTP/1.1" 500 62146
[4.33752315]
[1.38242052]
[24/Nov/2023 15:05:29] "POST /status/ml/ HTTP/1.1" 200 608
2023 ERA IP
[24/Nov/2023 15:05:32] "GET /status/statistics/ HTTP/1.1" 200 10063
Not Found: /robots.txt
[25/Nov/2023 02:50:46] "GET /robots.txt HTTP/1.1" 404 2221
2023 ERA IP
[25/Nov/2023 02:53:09] "GET /status/statistics/ HTTP/1.1" 200 10063
Not Found: /status/ã…¢/
[25/Nov/2023 10:28:46] "GET /status/%E3%85%A2/ HTTP/1.1" 404 2642
[9.34227183]
[3.6818251]
[25/Nov/2023 10:28:53] "GET /status/ml/ HTTP/1.1" 200 606
[4.33752315]
[1.38242052]
[25/Nov/2023 10:28:57] "POST /status/ml/ HTTP/1.1" 200 608
2023 ERA IP
[25/Nov/2023 10:29:09] "GET /status/statistics/ HTTP/1.1" 200 10063
2023 ERA IP
[26/Nov/2023 00:35:20] "POST /status/statistics/ HTTP/1.1" 200 10063
2023 ERA IP
[26/Nov/2023 00:35:56] "POST /status/statistics/ HTTP/1.1" 200 10063
[9.34227183]
[3.6818251]
[26/Nov/2023 00:35:59] "GET /status/ml/ HTTP/1.1" 200 606
[4.33752315]
[1.38242052]
[26/Nov/2023 00:36:13] "POST /status/ml/ HTTP/1.1" 200 608
[26/Nov/2023 00:36:16] "GET /status/ HTTP/1.1" 200 435262
2023 ERA IP
[26/Nov/2023 00:36:22] "GET /status/statistics/ HTTP/1.1" 200 10063
2023 W IP
[26/Nov/2023 00:36:26] "POST /status/statistics/ HTTP/1.1" 200 9843
2023 ERA IP
[26/Nov/2023 00:36:29] "POST /status/statistics/ HTTP/1.1" 200 10063
2023 G IP
[27/Nov/2023 08:25:16] "POST /status/statistics/ HTTP/1.1" 200 9980
2023 ERA IP
[27/Nov/2023 08:25:19] "POST /status/statistics/ HTTP/1.1" 200 10063
Not Found: /robots.txt
[27/Nov/2023 10:57:42] "GET /robots.txt HTTP/1.1" 404 2221
[9.34227183]
[3.6818251]
[27/Nov/2023 10:57:43] "GET /status/ml/ HTTP/1.1" 200 606
2023 W IP
[28/Nov/2023 16:59:01] "POST /status/statistics/ HTTP/1.1" 200 9843
2023 ERA IP
[28/Nov/2023 16:59:05] "POST /status/statistics/ HTTP/1.1" 200 10063
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).

You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
Error: That port is already in use.
2023 ERA H
[03/Dec/2023 02:32:11] "POST /status/statistics/ HTTP/1.1" 200 9903
2023 ERA IP
[03/Dec/2023 02:32:19] "POST /status/statistics/ HTTP/1.1" 200 10063
[9.34227183]
[3.6818251]
[03/Dec/2023 02:32:22] "GET /status/ml/ HTTP/1.1" 200 606
[4.33752315]
[1.38242052]
[03/Dec/2023 02:32:27] "POST /status/ml/ HTTP/1.1" 200 608
2023 ERA IP
[03/Dec/2023 02:32:31] "GET /status/statistics/ HTTP/1.1" 200 10063
2023 ERA IP
[03/Dec/2023 23:06:02] "POST /status/statistics/ HTTP/1.1" 200 10063
Not Found: /sitemap.xml.gz
[04/Dec/2023 05:28:41] "GET /sitemap.xml.gz HTTP/1.1" 404 2233
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).

You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
December 06, 2023 - 02:28:31
Django version 4.2.4, using settings 'kbo_demo.settings'
Starting development server at http://127.0.0.1:10000/
Quit the server with CONTROL-C.

2023 ERA IP
[06/Dec/2023 02:28:36] "POST /status/statistics/ HTTP/1.1" 200 10063
Not Found: /favicon.ico
[06/Dec/2023 02:28:37] "GET /favicon.ico HTTP/1.1" 404 2224
Not Found: /atom.xml
[06/Dec/2023 02:28:49] "GET /atom.xml HTTP/1.1" 404 2215
Not Found: /sitemaps.xml
[06/Dec/2023 02:54:06] "GET /sitemaps.xml HTTP/1.1" 404 2227
Not Found: /sitemap.xml
[06/Dec/2023 03:41:25] "GET /sitemap.xml HTTP/1.1" 404 2224
Not Found: /robots.txt
[06/Dec/2023 14:17:29] "GET /robots.txt HTTP/1.1" 404 2221
Not Found: /atom.xml
[06/Dec/2023 14:17:38] "GET /atom.xml HTTP/1.1" 404 2215
2023 ERA HR
[07/Dec/2023 00:41:30] "POST /status/statistics/ HTTP/1.1" 200 9741
2023 ERA IP
[07/Dec/2023 00:41:34] "POST /status/statistics/ HTTP/1.1" 200 10063
Not Found: /atom.xml
[07/Dec/2023 19:21:42] "GET /atom.xml HTTP/1.1" 404 2215
2023 ERA IP
[08/Dec/2023 09:49:40] "POST /status/statistics/ HTTP/1.1" 200 10063
2023 ERA HR
[11/Dec/2023 05:57:37] "POST /status/statistics/ HTTP/1.1" 200 9741
2023 ERA IP
[11/Dec/2023 05:57:41] "POST /status/statistics/ HTTP/1.1" 200 10063
2023 ERA IP
[11/Dec/2023 09:52:46] "POST /status/statistics/ HTTP/1.1" 200 10063
Not Found: /robots.txt
[11/Dec/2023 10:00:26] "GET /robots.txt HTTP/1.1" 404 2221
2023 ERA IP
[11/Dec/2023 10:00:27] "GET /status/statistics/ HTTP/1.1" 200 10063
Not Found: /robots.txt
[11/Dec/2023 10:30:29] "GET /robots.txt HTTP/1.1" 404 2221
Not Found: /robots.txt
[11/Dec/2023 10:30:30] "GET /robots.txt HTTP/1.1" 404 2221
Not Found: /robots.txt
[11/Dec/2023 10:30:30] "GET /robots.txt HTTP/1.1" 404 2221
Not Found: /robots.txt
[11/Dec/2023 10:30:31] "GET /robots.txt HTTP/1.1" 404 2221
Not Found: /sitemap.xml
[11/Dec/2023 10:30:32] "GET /sitemap.xml HTTP/1.1" 404 2224
[9.34227183]
[3.6818251]
[11/Dec/2023 10:30:42] "GET /status/ml/ HTTP/1.1" 200 606
2023 ERA IP
[11/Dec/2023 10:30:44] "GET /status/statistics/ HTTP/1.1" 200 10063
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).

You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
January 09, 2025 - 14:29:12
Django version 4.2.4, using settings 'kbo_demo.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).

You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
January 09, 2025 - 14:30:49
Django version 4.2.4, using settings 'kbo_demo.settings'
Starting development server at http://127.0.0.1:10000/
Quit the server with CONTROL-C.

Invalid HTTP_HOST header: '6da06bfc6fb7.ngrok.app'. You may need to add '6da06bfc6fb7.ngrok.app' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/Users/michaelkim/anaconda3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelkim/anaconda3/lib/python3.11/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelkim/anaconda3/lib/python3.11/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/Users/michaelkim/anaconda3/lib/python3.11/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '6da06bfc6fb7.ngrok.app'. You may need to add '6da06bfc6fb7.ngrok.app' to ALLOWED_HOSTS.
Bad Request: /
[09/Jan/2025 14:45:51] "GET / HTTP/1.1" 400 65329
Invalid HTTP_HOST header: '6da06bfc6fb7.ngrok.app'. You may need to add '6da06bfc6fb7.ngrok.app' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/Users/michaelkim/anaconda3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelkim/anaconda3/lib/python3.11/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelkim/anaconda3/lib/python3.11/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/Users/michaelkim/anaconda3/lib/python3.11/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '6da06bfc6fb7.ngrok.app'. You may need to add '6da06bfc6fb7.ngrok.app' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
[09/Jan/2025 14:45:51] "GET /favicon.ico HTTP/1.1" 400 65257
Not Found: /
[09/Jan/2025 15:13:38] "GET / HTTP/1.1" 404 2173
2023 ERA IP
[09/Jan/2025 15:13:50] "GET /status/statistics/ HTTP/1.1" 200 10063
2023 ERA IP
[09/Jan/2025 15:18:27] "GET /status/statistics/ HTTP/1.1" 200 10063
2023 ERA IP
2023 ERA IP
[09/Jan/2025 15:19:09] "GET /status/statistics/ HTTP/1.1" 200 10063
Not Found: /apple-touch-icon.png
[09/Jan/2025 15:19:09] "GET /apple-touch-icon.png HTTP/1.1" 404 2251
Not Found: /apple-touch-icon.png
Not Found: /apple-touch-icon-precomposed.png
[09/Jan/2025 15:19:09] "GET /status/statistics/ HTTP/1.1" 200 10063
[09/Jan/2025 15:19:09] "GET /apple-touch-icon.png HTTP/1.1" 404 2251
Not Found: /apple-touch-icon-precomposed.png
[09/Jan/2025 15:19:09] "GET /apple-touch-icon-precomposed.png HTTP/1.1" 404 2287
Not Found: /favicon.ico
[09/Jan/2025 15:19:09] "GET /apple-touch-icon-precomposed.png HTTP/1.1" 404 2287
Not Found: /favicon.ico
[09/Jan/2025 15:19:09] "GET /favicon.ico HTTP/1.1" 404 2224
[09/Jan/2025 15:19:09] "GET /favicon.ico HTTP/1.1" 404 2224
2023 ERA IP
[09/Jan/2025 15:19:39] "GET /status/statistics/ HTTP/1.1" 200 10063
Not Found: /favicon.ico
[09/Jan/2025 15:19:43] "GET /favicon.ico HTTP/1.1" 404 2224
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).

You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
January 09, 2025 - 15:27:15
Django version 4.2.4, using settings 'kbo_demo.settings'
Starting development server at http://127.0.0.1:10000/
Quit the server with CONTROL-C.

2023 ERA IP
[09/Jan/2025 15:28:23] "GET /status/statistics/ HTTP/1.1" 200 10063
